# -*- coding: utf-8 -*-
"""GIAODIEN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zjlTxPIjRz1_DNCxjifXUSzKPJkdz_e-
"""

#pip install -q streamlit pyngrok chromadb google-generativeai sentence-transformers

#from pyngrok import ngrok
#ngrok.kill()

#from pyngrok import ngrok

# 🔴 DÁN AUTHTOKEN NGROK CỦA BẠN VÀO ĐÂY
#ngrok.set_auth_token("37yCte3FbdYw4EUVaT6Ybq0JA8i_685ddwYPK6991hA5mSxow")

# from google.colab import drive
import os

# Mount trực tiếp, không cần xóa thủ công
# drive.mount('/content/drive', force_remount=True)
CHROMA_PATH = "/content/drive/MyDrive/my_chroma_db"
if os.path.exists(CHROMA_PATH):
    print("✅ Đã kết nối Drive. Thư mục Chroma TỒN TẠI.")
    print("Các tệp bên trong:", os.listdir(CHROMA_PATH))
else:
    print("❌ Vẫn không thấy thư mục. Hãy kiểm tra lại tên 'chroma_db_persist' trên Drive gốc.")


import streamlit as st
# import chromadb
# from chromadb.utils import embedding_functions
import google.generativeai as genai

# ================== CẤU HÌNH ==================
COLLECTION_NAME = "TTHC_rag"
EMBEDDING_MODEL = "BAAI/bge-m3"
CHROMA_PATH = "/content/drive/MyDrive/my_chroma_db"

import random
LIST_KEYS = [
     "AIzaSyBjxqE6-0noq3uoc5wHf5r7JGeabdNaW_c", # Key 1
     "AIzaSyDRHLndIRHGgk6_qWHsbIh-a2xpMdtvYYQ", # Key 2
     "AIzaSyC0xTwJrKD-lg9j5K0tkYlFfzZ-owpm6qo"  # Key 3
 ]
# Tự động chọn ngẫu nhiên 1 Key mỗi khi chạy lại giao diện
API_KEY = random.choice(LIST_KEYS)

genai.configure(api_key=API_KEY)
model = genai.GenerativeModel("gemini-2.5-flash")

 # ================== CHROMA ==================
embedding_function = embedding_functions.SentenceTransformerEmbeddingFunction(
    model_name=EMBEDDING_MODEL
)

client = chromadb.PersistentClient(path=CHROMA_PATH)

collection = client.get_or_create_collection(
    name=COLLECTION_NAME,
    embedding_function=embedding_function)

# ================== UI ==================
import streamlit as st

# =====================
# PAGE CONFIG
# =====================
st.set_page_config(
    page_title="Chatbot Thủ tục Khai tử",
    layout="wide",
    page_icon="🤖"
)

# =====================
# SESSION STATE
# =====================
if "messages" not in st.session_state:
    st.session_state.messages = []
# DARK CHAT CSS
st.markdown("""
<style>
.stApp {
    background: radial-gradient(circle at top, #1b2735, #090a0f);
    color: #eaeaea;
}

/* Header */
.header {
    display: flex;
    align-items: center;
    gap: 16px;
    background: linear-gradient(90deg, #0f2027, #203a43, #2c5364);
    padding: 22px 28px;
    border-radius: 18px;
    margin-bottom: 25px;
}
.header-icon { font-size: 40px; }
.header h1 { margin: 0; font-size: 26px; color: white; }
.header p { margin-top: 6px; font-size: 14px; opacity: 0.85; }

/* Chat */
.chat-container {
    max-width: 900px;
    margin: auto;
}

.user-bubble {
    background: linear-gradient(90deg, #0078d4, #00b4db);
    color: white;
    padding: 14px 18px;
    border-radius: 18px 18px 4px 18px;
    margin: 14px 0 14px auto;
    max-width: 75%;
}

.bot-bubble {
    background: rgba(255,255,255,0.06);
    border: 1px solid rgba(255,255,255,0.08);
    padding: 16px 18px;
    border-radius: 18px 18px 18px 4px;
    margin: 14px auto 14px 0;
    max-width: 75%;
}

/* Input */
.stTextInput input {
    background-color: #121826;
    color: white;
    border-radius: 12px;
    border: 1px solid #2e3a4d;
    height: 46px;
}

/* Button */
.stButton > button {
    background: linear-gradient(90deg, #0078d4, #00b4db);
    color: white;
    border-radius: 12px;
    height: 44px;
    border: none;
    font-weight: 600;
}
</style>
""", unsafe_allow_html=True)
 
# =====================
# HEADER
# =====================
st.markdown("""
<div class="header">
    <div class="header-icon">🤖</div>
    <div>
        <h1>Chatbot Hỏi đáp Thủ tục Khai tử</h1>
        <p>Trợ lý hành chính công – hỏi đáp liên tục về đăng ký khai tử</p>
    </div>
</div>
""", unsafe_allow_html=True)

# =====================
# CHAT HISTORY
# =====================
st.markdown('<div class="chat-container">', unsafe_allow_html=True)

for msg in st.session_state.messages:
    if msg["role"] == "user":
        st.markdown(
            f'<div class="user-bubble">🧑‍💼 {msg["content"]}</div>',
            unsafe_allow_html=True
        )
    else:
        st.markdown(
            f'<div class="bot-bubble">🤖 {msg["content"]}</div>',
            unsafe_allow_html=True
        )

st.markdown('</div>', unsafe_allow_html=True)

# =====================
# INPUT
# =====================
query = st.text_input(
    "💬 Nhập câu hỏi về thủ tục khai tử",
    placeholder="Ví dụ: Khai tử quá hạn có bị phạt không?"
)

send = st.button("🚀 Gửi")

# =====================
# HANDLE MESSAGE
# =====================
if send and query:
    # Lưu câu hỏi user
    st.session_state.messages.append({
        "role": "user",
        "content": query
    })

    with st.spinner("🤖 Chatbot đang tra cứu thông tin..."):
        # ===== RAG QUERY =====
        results = collection.query(
            query_texts=[query],
            n_results=3,
            include=["documents", "metadatas"]
        )

        # ===== BUILD CONTEXT + SOURCES =====
        context_parts = []
        for doc, meta in zip(results["documents"][0], results["metadatas"][0]):
            context_parts.append(
                f"[{meta['hierarchy']}]\n{doc}\n(Nguồn: {meta['url']})"
    )

        context = "\n\n".join(context_parts)
# ===== PROMPT =====
        prompt = f"""
Bạn là trợ lý hành chính công chuyên về thủ tục KHAI TỬ. Trả lời ngắn gọn, chính xác, có dẫn nguồn.
Câu trả lời cần ngắn gọn, chia rõ các bước 1, 2, 3 nếu có.
Context:
{context}

Câu hỏi: {query}

Trả lời bằng tiếng Việt:
"""
        response = model.generate_content(prompt)
        final_answer=response.text
        # Lưu vào lịch sử chat
        st.session_state.messages.append({
            "role": "assistant",
            "content": final_answer
        })
        st.rerun()


import chromadb

# Đường dẫn phải trỏ đúng vào thư mục chứa dữ liệu bạn đã tạo ở Notebook 1
CHROMA_PATH = "/content/drive/MyDrive/my_chroma_db"
COLLECTION_NAME = "TTHC_rag"
client = chromadb.PersistentClient(path=CHROMA_PATH)
collection = client.get_collection(name=COLLECTION_NAME)
print("Danh sách Collection hiện có:", client.list_collections())
# Dùng print để xem kết quả trong Notebook
print(f"Số lượng tài liệu đang có trong Database: {collection.count()}")



public_url = ngrok.connect(8501)
print("🌐 LINK CHATBOT:", public_url)
