# -*- coding: utf-8 -*-
"""KPDLCK.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vNc5-1FQ7DzH0AmMrDeN4808_AHmnEcf
"""

!pip install -q requests
!pip install -q bs4
!pip install -q html2text
!pip install -q chromadb
!pip install -q google-generativeai

import uuid
from datetime import date
import hashlib
import re
import json
import html2text

h = html2text.HTML2Text()
h.body_width = 0

import requests
import pandas as pd
from bs4 import BeautifulSoup
from urllib.parse import urlparse

import chromadb
from chromadb.utils import embedding_functions
import google.generativeai as genai

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_excel(
    "/content/drive/MyDrive/KPDL_CUOIKY/DM_TTHC (Phu luc QD 2650) thuộc thẩm quyền cấp XÃ.xlsx",
    sheet_name="XÃ",
    dtype=str
)

df_part_one = df.iloc[[252, 262, 265, 272, 275], :]

BASE_URL = "https://dichvucong.gov.vn/p/home/dvc-chi-tiet-thu-tuc-hanh-chinh.html"

HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0 Safari/537.36"
    )
}

DATA_FOLDER = "/content/drive/MyDrive/KPDL_CUOIKY"

def clean_text(text):
    return re.sub(r"\s+", " ", text).strip() if text else ""


def make_chunk(metadata, content, chunk_type, hierarchy, url, title, rows=0, cols=0):
    key = f"{url}{hierarchy}{content[:200]}"
    hash_id = hashlib.sha256(key.encode()).hexdigest()[:20]

    chunk = {
        "id": f"{hash_id}-{uuid.uuid4().hex[:8]}",
        "url": url,
        "title": title,
        "chunk_type": chunk_type,
        "hierarchy": hierarchy,
        "content_text": content.strip(),
        "metadata": {
            "source_domain": urlparse(url).netloc,
            "tokens": len(content.split()),
            "has_table": chunk_type == "table",
            "crawl_date": date.today().strftime("%Y-%m-%d"),
            "procedure_code": metadata.get("procedure_code", ""),
            "category": metadata.get("category", ""),
            "offical_annouce": metadata.get("offical_annouce", ""),
            "is_entire": metadata.get("is_entire", False)
        }
    }

    if chunk_type == "table":
        chunk["metadata"].update({
            "row_count": rows,
            "col_count": cols
        })

    return chunk


def count_table_cells(table):
    rows = table.find_all("tr")
    cols = 0
    if rows:
        cols = len(rows[0].find_all(["th", "td"]))
    return len(rows), cols
def crawl_and_chunk(metadata, url, headers):
    resp = requests.get(url, headers=headers, timeout=20)
    resp.encoding = "utf-8"
    soup = BeautifulSoup(resp.text, "html.parser")

    title = clean_text(soup.h1.get_text()) if soup.h1 else "Không có tiêu đề"
    chunks = []
    hierarchy_stack = []

    main = soup.find("div", class_="row")
    if main:
        main = main.find("div", class_="col-sm-8")
    if not main:
        main = soup.body

    def should_skip(elem):
        if not elem.get("class"):
            return False
        classes = " ".join(elem["class"])
        skip_words = [
            "breadcrumb", "header", "footer",
            "navbar", "sidebar", "related", "comment"
        ]
        return any(word in classes for word in skip_words)

    def process(elem):
        nonlocal hierarchy_stack

        if should_skip(elem):
            return False

        has_processed_child = False

        for child in elem.children:
            if getattr(child, "name", None):
                if process(child):
                    has_processed_child = True

        # TABLE
        if elem.name == "table" and not elem.get("data-processed"):
            md = h.handle(str(elem)).strip()
            if len(md) > 50:
                h_text = " > ".join(hierarchy_stack) or title
                rows, cols = count_table_cells(elem)
                chunks.append(
                    make_chunk(metadata, md, "table", h_text, url, title, rows, cols)
                )
                elem.attrs["data-processed"] = "true"
            return True

        # LIST
        if elem.name in ["ul", "ol"]:
            items = [
                clean_text(li.get_text())
                for li in elem.find_all("li", recursive=False)
            ]
            if items:
                content = "\n- " + "\n- ".join(items)
                h_text = " > ".join(hierarchy_stack) or title
                chunks.append(
                    make_chunk(metadata, content, "list", h_text, url, title)
                )
            return True

        # HEADER
        if elem.name in ["h1", "h2", "h3", "h4", "h5", "h6"]:
            level = int(elem.name[1])
            text = clean_text(elem.get_text())

            if len(hierarchy_stack) >= level:
                hierarchy_stack[level - 1] = text
                hierarchy_stack[:] = hierarchy_stack[:level]
            else:
                hierarchy_stack.append(text)

            h_text = " > ".join(hierarchy_stack)
            chunks.append(
                make_chunk(metadata, text, "header", h_text, url, title)
            )
            return True

        # PARAGRAPH
        if elem.name in ["p", "div", "section", "article"]:
            if has_processed_child or elem.get("data-processed"):
                return True

            text = clean_text(elem.get_text())
            if 15 < len(text) < 3000:
                h_text = " > ".join(hierarchy_stack) or title
                chunks.append(
                    make_chunk(metadata, text, "paragraph", h_text, url, title)
                )
            return True

        return has_processed_child

    for el in main.descendants:
        if getattr(el, "name", None):
            process(el)

    return chunks

data = []

for _, row in df_part_one.iterrows():
    metadata = {
        "procedure_code": row["Mã TTHC"],
        "category": row["LĨNH VỰC"].replace("\n", ""),
        "offical_annouce": row["QĐ CÔNG BỐ"],
        "is_entire": True if row["DVCTT Toàn trình"] == "X" else False
    }

    url = BASE_URL + f"?ma_thu_tuc={metadata['procedure_code']}"
    results = crawl_and_chunk(metadata, url, HEADERS)
    data += results

with open(f"{DATA_FOLDER}/TTHC.json", "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Đã lưu {len(data)} chunks vào TTHC.json")

JSON_FILE = f"{DATA_FOLDER}/TTHC.json"
COLLECTION_NAME = "TTHC_rag"
EMBEDDING_MODEL = "BAAI/bge-m3"

embedding_function = embedding_functions.SentenceTransformerEmbeddingFunction(
    model_name=EMBEDDING_MODEL
)

client = chromadb.PersistentClient(path="drive/MyDrive/my_chroma_db")
collection = client.get_or_create_collection(
    name=COLLECTION_NAME,
    embedding_function=embedding_function
)

with open(JSON_FILE, "r", encoding="utf-8") as f:
    data = json.load(f)

ids, documents, metadatas = [], [], []

for item in data:
    ids.append(item["id"])
    documents.append(item["content_text"])

    meta = item["metadata"].copy()
    meta.update({
        "url": item["url"],
        "title": item["title"],
        "hierarchy": item["hierarchy"],
        "chunk_type": item["chunk_type"],
        "domain": item["metadata"].get("source_domain", "unknown")
    })

    metadatas.append(meta)

collection.add(
    ids=ids,
    documents=documents,
    metadatas=metadatas
)

print(f"Đã đẩy {len(data)} chunks vào Chroma")

API_KEY = "AIzaSyBjxqE6-0noq3uoc5wHf5r7JGeabdNaW_c"
genai.configure(api_key=API_KEY)
model = genai.GenerativeModel("gemini-2.5-flash")

query = "Thủ tục khai tử"

results = collection.query(
    query_texts=[query],
    n_results=3,
    include=["documents", "metadatas", "distances"]
)

context_parts = []
for doc, meta in zip(results["documents"][0], results["metadatas"][0]):
    context_parts.append(
        f"[{meta['hierarchy']}]\n{doc}\n(Nguồn: {meta['url']})"
    )

context = "\n\n".join(context_parts)

prompt = f"""
Bạn là trợ lý hành chính công Việt Nam, trả lời ngắn gọn, chính xác, có dẫn nguồn.

Context:
{context}

Câu hỏi: {query}

Trả lời bằng tiếng Việt, có đánh số nếu là danh sách:
"""

response = model.generate_content(prompt)
print("Trả lời:\n", response.text)